/*
 * This file is generated by jOOQ.
 */
package com.aliBoard.jooq.tables.records;


import com.aliBoard.jooq.tables.MovieRelGenre;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieRelGenreRecord extends UpdatableRecordImpl<MovieRelGenreRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.movie_rel_genre.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.movie_rel_genre.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.movie_rel_genre.movie_id</code>.
     */
    public void setMovieId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.movie_rel_genre.movie_id</code>.
     */
    public Integer getMovieId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.movie_rel_genre.movie_genre_id</code>.
     */
    public void setMovieGenreId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.movie_rel_genre.movie_genre_id</code>.
     */
    public Integer getMovieGenreId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MovieRelGenre.MOVIE_REL_GENRE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return MovieRelGenre.MOVIE_REL_GENRE.MOVIE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return MovieRelGenre.MOVIE_REL_GENRE.MOVIE_GENRE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMovieId();
    }

    @Override
    public Integer component3() {
        return getMovieGenreId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMovieId();
    }

    @Override
    public Integer value3() {
        return getMovieGenreId();
    }

    @Override
    public MovieRelGenreRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MovieRelGenreRecord value2(Integer value) {
        setMovieId(value);
        return this;
    }

    @Override
    public MovieRelGenreRecord value3(Integer value) {
        setMovieGenreId(value);
        return this;
    }

    @Override
    public MovieRelGenreRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieRelGenreRecord
     */
    public MovieRelGenreRecord() {
        super(MovieRelGenre.MOVIE_REL_GENRE);
    }

    /**
     * Create a detached, initialised MovieRelGenreRecord
     */
    public MovieRelGenreRecord(Integer id, Integer movieId, Integer movieGenreId) {
        super(MovieRelGenre.MOVIE_REL_GENRE);

        setId(id);
        setMovieId(movieId);
        setMovieGenreId(movieGenreId);
    }
}
