/*
 * This file is generated by jOOQ.
 */
package com.aliBoard.jooq.tables.records;


import com.aliBoard.jooq.enums.Genre;
import com.aliBoard.jooq.tables.MovieGenre;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieGenreRecord extends UpdatableRecordImpl<MovieGenreRecord> implements Record2<Integer, Genre> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.movie_genre.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.movie_genre.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.movie_genre.movie_genre</code>.
     */
    public void setMovieGenre(Genre value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.movie_genre.movie_genre</code>.
     */
    public Genre getMovieGenre() {
        return (Genre) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Genre> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Genre> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MovieGenre.MOVIE_GENRE.ID;
    }

    @Override
    public Field<Genre> field2() {
        return MovieGenre.MOVIE_GENRE.MOVIE_GENRE_;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Genre component2() {
        return getMovieGenre();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Genre value2() {
        return getMovieGenre();
    }

    @Override
    public MovieGenreRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MovieGenreRecord value2(Genre value) {
        setMovieGenre(value);
        return this;
    }

    @Override
    public MovieGenreRecord values(Integer value1, Genre value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieGenreRecord
     */
    public MovieGenreRecord() {
        super(MovieGenre.MOVIE_GENRE);
    }

    /**
     * Create a detached, initialised MovieGenreRecord
     */
    public MovieGenreRecord(Integer id, Genre movieGenre) {
        super(MovieGenre.MOVIE_GENRE);

        setId(id);
        setMovieGenre(movieGenre);
    }
}
