/*
 * This file is generated by jOOQ.
 */
package com.aliBoard.jooq.tables.records;


import com.aliBoard.jooq.tables.Movie;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieRecord extends UpdatableRecordImpl<MovieRecord> implements Record12<Integer, String, String, Integer, String, Integer, String, String, String, LocalDate, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.movie.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.movie.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.movie.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.movie.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.movie.original_title</code>.
     */
    public void setOriginalTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.movie.original_title</code>.
     */
    public String getOriginalTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.movie.vimeo_id</code>.
     */
    public void setVimeoId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.movie.vimeo_id</code>.
     */
    public Integer getVimeoId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.movie.overview</code>.
     */
    public void setOverview(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.movie.overview</code>.
     */
    public String getOverview() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.movie.popularity</code>.
     */
    public void setPopularity(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.movie.popularity</code>.
     */
    public Integer getPopularity() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.movie.original_language</code>.
     */
    public void setOriginalLanguage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.movie.original_language</code>.
     */
    public String getOriginalLanguage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.movie.poster_path</code>.
     */
    public void setPosterPath(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.movie.poster_path</code>.
     */
    public String getPosterPath() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.movie.backdrop_path</code>.
     */
    public void setBackdropPath(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.movie.backdrop_path</code>.
     */
    public String getBackdropPath() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.movie.release_date</code>.
     */
    public void setReleaseDate(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.movie.release_date</code>.
     */
    public LocalDate getReleaseDate() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>public.movie.vote_average</code>.
     */
    public void setVoteAverage(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.movie.vote_average</code>.
     */
    public BigDecimal getVoteAverage() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.movie.vote_count</code>.
     */
    public void setVoteCount(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.movie.vote_count</code>.
     */
    public BigDecimal getVoteCount() {
        return (BigDecimal) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, Integer, String, Integer, String, String, String, LocalDate, BigDecimal, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, Integer, String, Integer, String, String, String, LocalDate, BigDecimal, BigDecimal> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Movie.MOVIE.ID;
    }

    @Override
    public Field<String> field2() {
        return Movie.MOVIE.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Movie.MOVIE.ORIGINAL_TITLE;
    }

    @Override
    public Field<Integer> field4() {
        return Movie.MOVIE.VIMEO_ID;
    }

    @Override
    public Field<String> field5() {
        return Movie.MOVIE.OVERVIEW;
    }

    @Override
    public Field<Integer> field6() {
        return Movie.MOVIE.POPULARITY;
    }

    @Override
    public Field<String> field7() {
        return Movie.MOVIE.ORIGINAL_LANGUAGE;
    }

    @Override
    public Field<String> field8() {
        return Movie.MOVIE.POSTER_PATH;
    }

    @Override
    public Field<String> field9() {
        return Movie.MOVIE.BACKDROP_PATH;
    }

    @Override
    public Field<LocalDate> field10() {
        return Movie.MOVIE.RELEASE_DATE;
    }

    @Override
    public Field<BigDecimal> field11() {
        return Movie.MOVIE.VOTE_AVERAGE;
    }

    @Override
    public Field<BigDecimal> field12() {
        return Movie.MOVIE.VOTE_COUNT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getOriginalTitle();
    }

    @Override
    public Integer component4() {
        return getVimeoId();
    }

    @Override
    public String component5() {
        return getOverview();
    }

    @Override
    public Integer component6() {
        return getPopularity();
    }

    @Override
    public String component7() {
        return getOriginalLanguage();
    }

    @Override
    public String component8() {
        return getPosterPath();
    }

    @Override
    public String component9() {
        return getBackdropPath();
    }

    @Override
    public LocalDate component10() {
        return getReleaseDate();
    }

    @Override
    public BigDecimal component11() {
        return getVoteAverage();
    }

    @Override
    public BigDecimal component12() {
        return getVoteCount();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getOriginalTitle();
    }

    @Override
    public Integer value4() {
        return getVimeoId();
    }

    @Override
    public String value5() {
        return getOverview();
    }

    @Override
    public Integer value6() {
        return getPopularity();
    }

    @Override
    public String value7() {
        return getOriginalLanguage();
    }

    @Override
    public String value8() {
        return getPosterPath();
    }

    @Override
    public String value9() {
        return getBackdropPath();
    }

    @Override
    public LocalDate value10() {
        return getReleaseDate();
    }

    @Override
    public BigDecimal value11() {
        return getVoteAverage();
    }

    @Override
    public BigDecimal value12() {
        return getVoteCount();
    }

    @Override
    public MovieRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MovieRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public MovieRecord value3(String value) {
        setOriginalTitle(value);
        return this;
    }

    @Override
    public MovieRecord value4(Integer value) {
        setVimeoId(value);
        return this;
    }

    @Override
    public MovieRecord value5(String value) {
        setOverview(value);
        return this;
    }

    @Override
    public MovieRecord value6(Integer value) {
        setPopularity(value);
        return this;
    }

    @Override
    public MovieRecord value7(String value) {
        setOriginalLanguage(value);
        return this;
    }

    @Override
    public MovieRecord value8(String value) {
        setPosterPath(value);
        return this;
    }

    @Override
    public MovieRecord value9(String value) {
        setBackdropPath(value);
        return this;
    }

    @Override
    public MovieRecord value10(LocalDate value) {
        setReleaseDate(value);
        return this;
    }

    @Override
    public MovieRecord value11(BigDecimal value) {
        setVoteAverage(value);
        return this;
    }

    @Override
    public MovieRecord value12(BigDecimal value) {
        setVoteCount(value);
        return this;
    }

    @Override
    public MovieRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, String value7, String value8, String value9, LocalDate value10, BigDecimal value11, BigDecimal value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieRecord
     */
    public MovieRecord() {
        super(Movie.MOVIE);
    }

    /**
     * Create a detached, initialised MovieRecord
     */
    public MovieRecord(Integer id, String title, String originalTitle, Integer vimeoId, String overview, Integer popularity, String originalLanguage, String posterPath, String backdropPath, LocalDate releaseDate, BigDecimal voteAverage, BigDecimal voteCount) {
        super(Movie.MOVIE);

        setId(id);
        setTitle(title);
        setOriginalTitle(originalTitle);
        setVimeoId(vimeoId);
        setOverview(overview);
        setPopularity(popularity);
        setOriginalLanguage(originalLanguage);
        setPosterPath(posterPath);
        setBackdropPath(backdropPath);
        setReleaseDate(releaseDate);
        setVoteAverage(voteAverage);
        setVoteCount(voteCount);
    }
}
