/*
 * This file is generated by jOOQ.
 */
package com.aliBoard.jooq.tables.records;


import com.aliBoard.jooq.enums.Payment;
import com.aliBoard.jooq.enums.ProfileStatus;
import com.aliBoard.jooq.tables.UserProfile;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfileRecord extends UpdatableRecordImpl<UserProfileRecord> implements Record9<Integer, ProfileStatus, String, String, String, LocalDate, Payment, LocalDate, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_profile.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_profile.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_profile.status</code>.
     */
    public void setStatus(ProfileStatus value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_profile.status</code>.
     */
    public ProfileStatus getStatus() {
        return (ProfileStatus) get(1);
    }

    /**
     * Setter for <code>public.user_profile.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_profile.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_profile.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_profile.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user_profile.telephone</code>.
     */
    public void setTelephone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_profile.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user_profile.birthday</code>.
     */
    public void setBirthday(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_profile.birthday</code>.
     */
    public LocalDate getBirthday() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.user_profile.payment_method</code>.
     */
    public void setPaymentMethod(Payment value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_profile.payment_method</code>.
     */
    public Payment getPaymentMethod() {
        return (Payment) get(6);
    }

    /**
     * Setter for <code>public.user_profile.registry_date</code>.
     */
    public void setRegistryDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user_profile.registry_date</code>.
     */
    public LocalDate getRegistryDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>public.user_profile.unsubscribe_date</code>.
     */
    public void setUnsubscribeDate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user_profile.unsubscribe_date</code>.
     */
    public LocalDate getUnsubscribeDate() {
        return (LocalDate) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, ProfileStatus, String, String, String, LocalDate, Payment, LocalDate, LocalDate> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, ProfileStatus, String, String, String, LocalDate, Payment, LocalDate, LocalDate> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserProfile.USER_PROFILE.ID;
    }

    @Override
    public Field<ProfileStatus> field2() {
        return UserProfile.USER_PROFILE.STATUS;
    }

    @Override
    public Field<String> field3() {
        return UserProfile.USER_PROFILE.NAME;
    }

    @Override
    public Field<String> field4() {
        return UserProfile.USER_PROFILE.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return UserProfile.USER_PROFILE.TELEPHONE;
    }

    @Override
    public Field<LocalDate> field6() {
        return UserProfile.USER_PROFILE.BIRTHDAY;
    }

    @Override
    public Field<Payment> field7() {
        return UserProfile.USER_PROFILE.PAYMENT_METHOD;
    }

    @Override
    public Field<LocalDate> field8() {
        return UserProfile.USER_PROFILE.REGISTRY_DATE;
    }

    @Override
    public Field<LocalDate> field9() {
        return UserProfile.USER_PROFILE.UNSUBSCRIBE_DATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public ProfileStatus component2() {
        return getStatus();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getTelephone();
    }

    @Override
    public LocalDate component6() {
        return getBirthday();
    }

    @Override
    public Payment component7() {
        return getPaymentMethod();
    }

    @Override
    public LocalDate component8() {
        return getRegistryDate();
    }

    @Override
    public LocalDate component9() {
        return getUnsubscribeDate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public ProfileStatus value2() {
        return getStatus();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getTelephone();
    }

    @Override
    public LocalDate value6() {
        return getBirthday();
    }

    @Override
    public Payment value7() {
        return getPaymentMethod();
    }

    @Override
    public LocalDate value8() {
        return getRegistryDate();
    }

    @Override
    public LocalDate value9() {
        return getUnsubscribeDate();
    }

    @Override
    public UserProfileRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserProfileRecord value2(ProfileStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public UserProfileRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserProfileRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserProfileRecord value5(String value) {
        setTelephone(value);
        return this;
    }

    @Override
    public UserProfileRecord value6(LocalDate value) {
        setBirthday(value);
        return this;
    }

    @Override
    public UserProfileRecord value7(Payment value) {
        setPaymentMethod(value);
        return this;
    }

    @Override
    public UserProfileRecord value8(LocalDate value) {
        setRegistryDate(value);
        return this;
    }

    @Override
    public UserProfileRecord value9(LocalDate value) {
        setUnsubscribeDate(value);
        return this;
    }

    @Override
    public UserProfileRecord values(Integer value1, ProfileStatus value2, String value3, String value4, String value5, LocalDate value6, Payment value7, LocalDate value8, LocalDate value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfileRecord
     */
    public UserProfileRecord() {
        super(UserProfile.USER_PROFILE);
    }

    /**
     * Create a detached, initialised UserProfileRecord
     */
    public UserProfileRecord(Integer id, ProfileStatus status, String name, String email, String telephone, LocalDate birthday, Payment paymentMethod, LocalDate registryDate, LocalDate unsubscribeDate) {
        super(UserProfile.USER_PROFILE);

        setId(id);
        setStatus(status);
        setName(name);
        setEmail(email);
        setTelephone(telephone);
        setBirthday(birthday);
        setPaymentMethod(paymentMethod);
        setRegistryDate(registryDate);
        setUnsubscribeDate(unsubscribeDate);
    }
}
