/*
 * This file is generated by jOOQ.
 */
package com.aliBoard.jooq.tables;


import com.aliBoard.jooq.Keys;
import com.aliBoard.jooq.Public;
import com.aliBoard.jooq.tables.records.MovieRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movie extends TableImpl<MovieRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.movie</code>
     */
    public static final Movie MOVIE = new Movie();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MovieRecord> getRecordType() {
        return MovieRecord.class;
    }

    /**
     * The column <code>public.movie.id</code>.
     */
    public final TableField<MovieRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.movie.title</code>.
     */
    public final TableField<MovieRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.movie.original_title</code>.
     */
    public final TableField<MovieRecord, String> ORIGINAL_TITLE = createField(DSL.name("original_title"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.movie.vimeo_id</code>.
     */
    public final TableField<MovieRecord, Integer> VIMEO_ID = createField(DSL.name("vimeo_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.movie.overview</code>.
     */
    public final TableField<MovieRecord, String> OVERVIEW = createField(DSL.name("overview"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.movie.popularity</code>.
     */
    public final TableField<MovieRecord, Integer> POPULARITY = createField(DSL.name("popularity"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.movie.original_language</code>.
     */
    public final TableField<MovieRecord, String> ORIGINAL_LANGUAGE = createField(DSL.name("original_language"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.movie.poster_path</code>.
     */
    public final TableField<MovieRecord, String> POSTER_PATH = createField(DSL.name("poster_path"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.movie.backdrop_path</code>.
     */
    public final TableField<MovieRecord, String> BACKDROP_PATH = createField(DSL.name("backdrop_path"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.movie.release_date</code>.
     */
    public final TableField<MovieRecord, LocalDate> RELEASE_DATE = createField(DSL.name("release_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.movie.vote_average</code>.
     */
    public final TableField<MovieRecord, BigDecimal> VOTE_AVERAGE = createField(DSL.name("vote_average"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.movie.vote_count</code>.
     */
    public final TableField<MovieRecord, BigDecimal> VOTE_COUNT = createField(DSL.name("vote_count"), SQLDataType.NUMERIC, this, "");

    private Movie(Name alias, Table<MovieRecord> aliased) {
        this(alias, aliased, null);
    }

    private Movie(Name alias, Table<MovieRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.movie</code> table reference
     */
    public Movie(String alias) {
        this(DSL.name(alias), MOVIE);
    }

    /**
     * Create an aliased <code>public.movie</code> table reference
     */
    public Movie(Name alias) {
        this(alias, MOVIE);
    }

    /**
     * Create a <code>public.movie</code> table reference
     */
    public Movie() {
        this(DSL.name("movie"), null);
    }

    public <O extends Record> Movie(Table<O> child, ForeignKey<O, MovieRecord> key) {
        super(child, key, MOVIE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<MovieRecord, Integer> getIdentity() {
        return (Identity<MovieRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MovieRecord> getPrimaryKey() {
        return Keys.MOVIE_PKEY;
    }

    @Override
    public List<UniqueKey<MovieRecord>> getKeys() {
        return Arrays.<UniqueKey<MovieRecord>>asList(Keys.MOVIE_PKEY);
    }

    @Override
    public Movie as(String alias) {
        return new Movie(DSL.name(alias), this);
    }

    @Override
    public Movie as(Name alias) {
        return new Movie(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Movie rename(String name) {
        return new Movie(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Movie rename(Name name) {
        return new Movie(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, Integer, String, Integer, String, String, String, LocalDate, BigDecimal, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
