/*
 * This file is generated by jOOQ.
 */
package com.aliBoard.jooq;


import com.aliBoard.jooq.tables.Movie;
import com.aliBoard.jooq.tables.MovieGenre;
import com.aliBoard.jooq.tables.MovieRelGenre;
import com.aliBoard.jooq.tables.UserProfile;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.movie</code>.
     */
    public final Movie MOVIE = Movie.MOVIE;

    /**
     * The table <code>public.movie_genre</code>.
     */
    public final MovieGenre MOVIE_GENRE = MovieGenre.MOVIE_GENRE;

    /**
     * The table <code>public.movie_rel_genre</code>.
     */
    public final MovieRelGenre MOVIE_REL_GENRE = MovieRelGenre.MOVIE_REL_GENRE;

    /**
     * The table <code>public.user_profile</code>.
     */
    public final UserProfile USER_PROFILE = UserProfile.USER_PROFILE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.MOVIE_GENRE_ID_SEQ,
            Sequences.MOVIE_ID_SEQ,
            Sequences.MOVIE_REL_GENRE_ID_SEQ,
            Sequences.USER_PROFILE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Movie.MOVIE,
            MovieGenre.MOVIE_GENRE,
            MovieRelGenre.MOVIE_REL_GENRE,
            UserProfile.USER_PROFILE);
    }
}
