/*
 * This file is generated by jOOQ.
 */
package com.aliBoard.jooq;


import com.aliBoard.jooq.tables.Movie;
import com.aliBoard.jooq.tables.MovieGenre;
import com.aliBoard.jooq.tables.MovieRelGenre;
import com.aliBoard.jooq.tables.UserProfile;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.movie</code>.
     */
    public static final Movie MOVIE = Movie.MOVIE;

    /**
     * The table <code>public.movie_genre</code>.
     */
    public static final MovieGenre MOVIE_GENRE = MovieGenre.MOVIE_GENRE;

    /**
     * The table <code>public.movie_rel_genre</code>.
     */
    public static final MovieRelGenre MOVIE_REL_GENRE = MovieRelGenre.MOVIE_REL_GENRE;

    /**
     * The table <code>public.user_profile</code>.
     */
    public static final UserProfile USER_PROFILE = UserProfile.USER_PROFILE;
}
