/*
 * This file is generated by jOOQ.
 */
package com.aliBoard.jooq;


import com.aliBoard.jooq.tables.Company;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;
}
